- name: aviad_and_noga_mobiles
  platform: group
  services:
    - service: mobile_app_aviad_phone
    - service: mobile_app_noga_phone

- platform: telegram
  name: "Home Assistant Telegram"
  chat_id: !secret telegram_chat_id